spring.application.name=CwhNaukariPortal
server.port=9696

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/JobPortal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (must be >= 32 chars for HMAC-SHA256)
app.jwt=uh38ru8y9ue98ferr89r8r89hrur8r8h9rre989e98

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
